spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://mohammedavez125_db_user:2004@production.fdkgzac.mongodb.net/master?retryWrites=true&w=majority

#spring.security.user.name=avez
#spring.security.user.password=2004
#spring.security.user.roles=ADMIN

springdoc.swagger-ui.path=/swagger-ui.html